public void add(LoggingEvent event){
if(event.getLevel() == null){
		event.setLevel(Level.INFO);
	}
	if(event.getLevel().equals(Level.ERROR)){
		errorCount++;
	}
	if(event.getLevel().equals(Level.WARN)){
		warnCount++;
	}
	if(event.getLevel().equals(Level.INFO)){
		infoCount++;
	}
	if(event.getLevel().equals(Level.DEBUG)){
		debugCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals(Level.FATAL)){
		fatalCount++;
	}
	if(event.getLevel().equals
}